export const AUTHENTICATION_NO = "AUTHENTICATION_NO"
export const AUTHENTICATION = "AUTHENTICATION"
export const GET_ANIMAL_PENDING = "GET_ANIMAL_PENDING"
export const GET_ANIMAL_SUCCESS = "GET_ANIMAL_SUCCESS"
export const GET_ANIMAL_FAIL = "GET_ANIMAL_FAIL"

